language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  matrix:
  - CI=true
script:
- npm run docs:build
deploy:
  provider: npm
  email: 781349304@qq.com
  api_key:
    secure: 158URjE/EZkuAs8hyiyRbhfTpP/q5TShHEDy9mni+uOno+b/VQawYG1tsDS2mEhSLDg8Fnz1eW4Rlc4ykKVMbM2TdPx5TEWX43Xdy1//O0jMm0HGkQjtBhWXBZSTqjCo60q5uPpzl6R76vhPH2XVe5G4K4vLfg1r7RsbEOe+sYO054jzZmPxdE+0kosb0akzR+kcFmQLQ0MwjMpLnYqemSRZGYf+XhpevdtvWVMuL/NVESwC32+r8BP/AJ1ss66xcQDhIQCD5vmbiDLXNngx0pAXl70eiyCD4a4+134VahF5sSJvcvLYbBQnBnHHGI0cD+yr5tvOEyvNIOsLX2YiKS9N1p+2yTc5d6QG2gnCA++fb4egdHWaxFKvBl/j7j/+bDC/5UIWbVc21pMLR/cvQAQnPvtC3Y0zyLrK46CV6I6hOUwQwJVh1skcVDghUACE6pMK2LEJwE7NMlwHaDtqlf2fCFK6qMWF+eWFssY5GoydsDgV9XRCGkfA/okK5/C8q/smNignyYkV6rblL2dnRB09OVnTMArdq2T2HTV2sEEve4r2gKl+/SwCffyYXkwYeDBokxI+gD1c9K3JfNtB9C3qfz+O+l2iMKll/iWFa1NMg3mWAh/BQkA5DFpnGTrmbtnEWEUU/eqiKi48ULHGmSuqMmq8rCvzU1RU2DfeNPE=
  on:
    # tags: true
    repo: LagrangeLabs/ii-hooks
    branch: main
  skip_cleanup: 'true'
